#' Create a treemap of files in a directory
#'
#' This function generates a treemap of files by size in a given directory using the
#' `elm_treemap` function. By default, both files and directories are included,
#' but files can be excluded by setting `dir_only` to TRUE.
#'
#' @param path A character string specifying the path to the directory of interest.
#' @param dir_only A logical value indicating whether to limit results to directories only. Default is FALSE.
#' @param interactive A logical value indicating whether to display the treemap interactively using the `highcharter` package. Default is TRUE.
#' @param ... Additional arguments to be passed to `get_files_tibble()`.
#'
#' @return A treemap of the files in the specified directory.
#'
#' @importFrom highcharter hchart hc_exporting hc_title hc_tooltip hcaes
#' @importFrom dplyr mutate
#'
#' @examples
#' elm_treemap_files("~/Documents/")
#' @export
elm_treemap_files <- function(path = ".",
                              dir_only = F,
                              interactive = TRUE,
                              ...) {
  data <- get_files_tibble(path = path, dir_only = dir_only, ...)
  elm_treemap(data, "files treemap",  interactive = interactive)
}

#' Create a treemap of directories in a directory
#'
#' This function generates a treemap of directories in a given directory using the `elm_treemap` function. By default, only directories are included, but files can be included by setting `dir_only` to FALSE.
#'
#' @param path A character string specifying the path to the directory of interest.
#' @param dir_only A logical value indicating whether to limit results to directories only. Default is TRUE.
#' @param interactive A logical value indicating whether to display the treemap interactively using the `highcharter` package. Default is TRUE.
#' @param ... Additional arguments to be passed to `get_files_tibble()`.
#'
#' @return A treemap of the directories in the specified directory.
#'
#' @importFrom highcharter hchart hc_exporting hc_title hc_tooltip hcaes
#' @importFrom dplyr mutate
#' @export
#' @examples
#' elm_treemap_folders("~/Documents/")
elm_treemap_folders <- function(path = ".",
                                dir_only = T,
                                interactive = TRUE,
                                ...) {
  data <- get_files_tibble(path = path, dir_only = dir_only, ...)
  elm_treemap(data, "folders treemap", interactive = interactive)
}

#' Generate a treemap using the `highcharter` or `treemap` package
#'
#' This function generates a treemap using either the `highcharter` or `treemap` package, depending on the value of the `interactive` parameter.
#'
#' @param files_tibble A tibble of file information generated by `get_files_tibble()`.
#' @param title A character string specifying the title of the treemap.
#' @param interactive A logical value indicating whether to display the treemap interactively using the `highcharter` package. Default is TRUE.
#'
#' @return A treemap of the files or directories in the specified directory.
#'
#' @importFrom highcharter hchart hc_title hc_tooltip hcaes
#' @importFrom treemap treemap
#' @importFrom dplyr mutate
#' @importFrom highcharter hc_exporting
#'
#' @export
#' @examples
#' \dontrun{
#' elm_treemap(get_files_tibble("~/Documents/"))
#' }
elm_treemap <- function(files_tibble,
                        title = "Files or folders treemap",
                        interactive = TRUE) {
  if (interactive) {
    files_tibble %>%
      highcharter::hchart(
        type = "treemap",
        highcharter::hcaes(
          x = file,
          color = bytes,
          value = bytes,
          size = size_chr,
          allowDrillToNode = TRUE
        )
      ) %>%
      highcharter::hc_tooltip(pointFormat = "{point.file}: {point.size}") %>%
      highcharter::hc_title(text = title) %>%
      highcharter::hc_exporting(enabled = TRUE)
  } else{
    files_tibble %>%
      dplyr::mutate(index = paste(file, size_chr, sep = ": ")) %>%
      treemap::treemap(
        index = c("index"),
        vSize = "bytes",
        vColor = "bytes",
        type = "value",
        title = title
      )
  }
}
