#' Create a sunburst of files in a directory
#'
#' This function generates a sunburst of files in a given directory using the `elm_sunburst` function. By default, both files and directories are included, but files can be excluded by setting `dir_only` to TRUE.
#'
#' @param path A character string specifying the path to the directory of interest.
#' @param dir_only A logical value indicating whether to limit results to directories only. Default is FALSE.
#' @param ... Additional arguments to be passed to `get_files_tibble()`.
#'
#' @return A sunburst of the files in the specified directory.
#'
#' @examples
#' \dontrun{
#' elm_sunburst_files("~/Documents/")
#' }
#' @export
elm_sunburst_files <- function(path = ".",
                              dir_only = F,
                              ...) {
  data <- get_data_tree(path = path, dir_only = dir_only, ...)
  elm_sunburst(data, "files sunburst")
}

#' Create a sunburst of directories in a directory
#'
#' This function generates a sunburst of directories in a given directory using
#' the `elm_sunburst` function. By default, only directories are included, but
#' files can be included by setting `dir_only` to FALSE.
#'
#' @param path A character string specifying the path to the directory of interest.
#' @param dir_only A logical value indicating whether to limit results to directories only. Default is TRUE.
#' @param ... Additional arguments to be passed to `get_files_tibble()`.
#'
#' @return A sunburst of the directories in the specified directory.

#' @examples
#' \dontrun{
#' elm_sunburst_folders("~/Documents/")
#' }
elm_sunburst_folders <- function(path = ".",
                                dir_only = T,
                                ...) {
  data <- get_data_tree(path = path, dir_only = dir_only, ...)
  elm_sunburst(data, "folders sunburst")
}

#' Generate a sunburst using the `sunburstR` package
#'
#' This function generates a sunburst using the sunburstR package.
#'
#' @param data_tree_tibble A tibble of data tree information generated by `get_data_tree()`.
#' @param title A character string specifying the title of the sunburst.
#'
#' @return A sunburst of the files or directories in the specified directory.
#'
#' @importFrom dplyr mutate
#' @importFrom dplyr as_tibble
#' @importFrom dplyr select
#' @importFrom data.tree ToDataFrameTypeCol
#' @importFrom sunburstR sund2b
#' @importFrom htmltools code
#' @importFrom htmlwidgets prependContent
#' @importFrom d3r d3_nest
#'
#' @export
#' @examples
#' \dontrun{
#' elm_sunburst(get_data_tree())
#' }
elm_sunburst <- function(data_tree_tibble,
                        title = "Files or folders sunburst") {
  networkDf <- data.tree::ToDataFrameTypeCol(data_tree_tibble, 'size') %>%
    dplyr::as_tibble() %>%
    dplyr::select(-1)
  networkNested <- d3r::d3_nest(
    networkDf,
    value_cols = c("size"),
    root = "root"
  )
  sn <- sunburstR::sund2b(
    networkNested,
    valueField = "size",
    showLabels = T,
    rootLabel = "root"
  )
  sn <- htmlwidgets::prependContent(sn, htmltools::code("disk usage (in bytes)"))
  sn
}
